os:
  - linux

language: php

php:
  - "7.2"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan key:generate
  - php artisan install:passport

script:
  - vendor/bin/phpunit