language: php

php:
  - "7.2"

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan key:generate
  - php artisan passport:install

script:
  - vendor/bin/phpunit